[[redirects]]
from = "/*"
to = "/index.html"
status = 200
[[redirects]]
  from = "/"
  to = "/register"
  status = 200
  edge_handler = "filterRequests"
[[redirects]]
  from = "/Dashboard"
  to = "/sharesdash"
  status = 200
  edge_handler = "filterRequests"
  